config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'google_authentication/login'
  get 'oauth2callback/check'
  get 'search/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/google_authentication_controller.rb
require 'google/apis/drive_v2'
require 'google/api_client/client_secrets'

class GoogleAuthenticationController < ApplicationController
  def login
    redirect_to(GoogleClient.new.authorization_uri)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/oauth2callback_controller.rb
require 'google/apis/drive_v2'
require 'google/api_client/client_secrets'
require 'json'

class Oauth2callbackController < ApplicationController
  def check
    if request['code'].nil?
      render 'failure'
    else
      google_client = GoogleClient.new
      google_client.fetch_access_token!(request['code'])
      cookies[:access_token] = google_client.access_token
      cookies[:refresh_token] = google_client.refresh_token
      cookies[:expires_in] = google_client.expires_in
      cookies[:issued_at] = google_client.issued_at
      @files = google_client.all_files
      render 'success'
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    client = GoogleClient.new
    client.atoken(cookies[:access_token])
    client.rtoken(cookies[:refresh_token])
    client.expiration(cookies[:expires_in])
    client.issued(cookies[:issued_at])
    @searched_files = client.show_files(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="jumbotron center">
  <h1>
    RailsApp</h1>
  <h2>
    Authorize us to access your Google Drive account
  </h2>
  <div>
    <%= link_to 'AUTHORIZE', {controller: "google_authentication", action: "login"}, class: "btn btn-danger btn-xlarge" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/oauth2callback/failure.html.erb
<div class="denied center">
  <h1>
    Access has been denied by user!
  </h1>
</div>

app/views/oauth2callback/success.html.erb
<div class="center">
  <h1>
    You have successfully registered!
  </h1>
  <h3>
    Here you can search your files!
  </h3>
    <p>
      <%= form_tag(search_show_path, method: :get) do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
      <% end %>
    </p>
  <h3>
    List of all files on your Google Drive account:
  </h3>
  <br>
  <table border="1px solid black">
    <thead>
      <tr >
        <th>
          Picture
        </th>
        <th>
          Title
        </th>
        <th>
          Last modified date
        </th>
        <th>
          Owner
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <% @files.items.each do |i|  %>
            <br>
            <%= image_tag i.icon_link %>
          <% end %>
        </td>
        <td>
          <% @files.items.each do |i|  %>
            <br>
            <%= i.title %>
          <% end %>
        </td>
        <td>
          <% @files.items.each do |i|  %>
            <br>
            <%= i.modified_date %>
          <% end %>
        </td>
        <td>
          <% @files.items.each do |i|  %>
            <br>
            <%= i.owner_names.slice!(0) %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/search/show.html.erb
<div class="center">
  <h3>
    List of all files on your Google Drive account containing  <%= params[:search] %>
  </h3>
  <br>
<table border="1px solid black">
  <thead>
    <tr>
      <th>
        Title
      </th>
      <th>
        Owner
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <% @searched_files.items.each do |i|  %>
          <br>
          <%= i.title %>
        <% end %>
      </td>
      <td>
        <% @searched_files.items.each do |i|  %>
          <br>
          <%= i.owner_names.slice!(0) %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
</div>